name: myapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.6  # Añade esta línea para el paquete de video
  fluent_ui: ^4.9.2
  cupertino_icons: ^1.0.6
  http: ^0.13.3  # Añadimos la dependencia http aquí

dev_dependencies:
  flutter_test:
    sdk: flutter
  weather_icons: ^3.0.0 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true